# Generated by Django 4.1.3 on 2023-11-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar_customuser_small_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='small_avatar',
        ),
    ]
